### ISSUE TITLE
Needs examples

### ISSUE THREAD

**Issue by marcoarruda** [GT-RAIL/rms#33]
I had no problem during the installation, also to create my account and login, but i'd like to see something running
I didn't understand yet how it works.
Thanks =D

**Comment by rctoris** [comment]
Great to hear!

Have you checked out the interface tutorial here: http://wiki.ros.org/rms/Tutorials/AGuideToInterfaceDevelopment

This is also a link to a demo interface we use here in the lab: https://github.com/WPI-RAIL/CarlDemoInterface
