### ISSUE TITLE
Missing tables and undefined variables

### ISSUE THREAD

**Issue by monsterlane** [GT-RAIL/rms#35]
First time installing on Ubuntu 14.04 and I'm getting a lot of errors when visiting localhost.

Missing Database Table
Error: Table settings for model Setting was not found in datasource default.

Notice (8): Undefined variable: loggedIn [APP/View/Elements/menu.ctp, line 42]

**Comment by cjds** [comment]
It seems like you can't access your database. Are you sure you have the correct credentials? Go to `app/Config/database.php` and check if those credentials will allow you to log into your `localhost/phpmyadmin`

**Comment by monsterlane** [comment]
From the terminal I can connect to mysql using mysql -u rms -p and entering the password from app/Config/database. If I type use rms; show tables; I see the following list of tables;

mysql> show tables;
+---------------------+
| Tables_in_rms       |
+---------------------+
| analytics           |
| anonymous_users     |
| appointments        |
| articles            |
| colladas            |
| conditions          |
| emails              |
| environments        |
| htn_stores          |
| ifaces              |
| ifaces_environments |
+---------------------+
11 rows in set (0.00 sec)

**Comment by cjds** [comment]
There definitely aren't enough tables there. 

I just tried installing it on a fresh VM of Ubuntu and it seems to be working fine. These are the tables that should be there

+---------------------+
| Tables_in_rms       |
+---------------------+
| appointments        |
| articles            |
| colladas            |
| conditions          |
| emails              |
| environments        |
| ifaces              |
| ifaces_environments |
| ims                 |
| logs                |
| markers             |
| mjpegs              |
| pages               |
| protocols           |
| resources           |
| roles               |
| rosbridges          |
| settings            |
| slots               |
| streams             |
| studies             |
| subscriptions       |
| teleops             |
| tfs                 |
| types               |
| urdfs               |
| users               |
+---------------------+

I would recommend trying to reinstall

**Comment by monsterlane** [comment]
I cloned the repo and ran the installer. Downloading the 2.0.8 release worked. I'll close this issue but there's something broken in master.
